### ISSUE TITLE
ModuleNotFoundError: No module named 'celery_app'

### ISSUE THREAD

**Issue by 885783558** [twtrubiks/docker-django-celery-tutorial#3]
您好，感谢您提供的一系列教程，正在学习中，我在 docker-compose up 的时候遇到了
“ModuleNotFoundError: No module named 'celery_app'”的问题，不知道怎么解决，求助。
以下是报错内容：
celery_1  | Traceback (most recent call last):
celery_1  |   File "/usr/local/bin/celery", line 11, in <module>
celery_1  |     sys.exit(main())
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 14, in main
celery_1  |     _main()
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 326, in main
celery_1  |     cmd.execute_from_commandline(argv)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 488, in execute_from_commandline
celery_1  |     super(CeleryCommand, self).execute_from_commandline(argv)))
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 279, in execute_from_commandline
celery_1  |     argv = self.setup_app_from_commandline(argv)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 481, in setup_app_from_commandline
celery_1  |     self.app = self.find_app(app)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 503, in find_app
celery_1  |     return find_app(app, symbol_by_name=self.symbol_by_name)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 355, in find_app
celery_1  |     sym = symbol_by_name(app, imp=imp)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 506, in symbol_by_name
celery_1  |     return imports.symbol_by_name(name, imp=imp)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 56, in symbol_by_name
celery_1  |     module = imp(module_name, package=package, **kwargs)
celery_1  |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 101, in import_from_cwd
celery_1  |     return imp(module, package=package)
celery_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
celery_1  |     return _bootstrap._gcd_import(name[level:], package, level)
celery_1  |   File "<frozen importlib._bootstrap>", line 978, in _gcd_import
celery_1  |   File "<frozen importlib._bootstrap>", line 961, in _find_and_load
celery_1  |   File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
celery_1  | ModuleNotFoundError: No module named 'celery_app'

**Comment by twtrubiks** [comment]
應該只是單純你在錯的路徑上執行
